### PR TITLE
Counting effect and some extra

### PR DESCRIPTION
**Pull request by FSBM**
- Added a **counting animation** for daily users and today's users using JS.
- **Fixed some error**s in responsiveness.
- Added more effects.
- Made the dark theme as a default theme.

https://github.com/user-attachments/assets/da4c75cc-2b87-448f-83a4-88506b82f8e4

### CODE REVIEW

**Comment by KorryKatti** [comment]
Thanks for the PR , will look into it and merge it

**Comment by KorryKatti** [comment]
@FSBM it seems you have removed the bottom row of image , 

the top row was contributors to Mirage's server and bottom for Mirage-web , kindly fix it

**Comment by FSBM** [comment]
Ok i'll change that

**Comment by FSBM** [comment]
I've done a new pull request by adding the bottom row.

**Pull request closed without merging**
